import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.destinations': 'Destinations',
    'nav.safaris': 'Safaris',
    'nav.services': 'Services',
    'nav.gallery': 'Gallery',
    'nav.blog': 'Blog',
    'nav.qa': 'Q&A',
    'nav.contact': 'Contact',
    'nav.bookNow': 'Book Now',
    'nav.kenya': 'Kenya',
    'nav.tanzania': 'Tanzania',
    
    // Hero Slider
    'hero.slide1.title': 'Discover the Magic of Africa',
    'hero.slide1.subtitle': 'Unforgettable Safari Adventures',
    'hero.slide1.description': 'Experience the raw beauty of Kenya and Tanzania with our expertly curated wildlife safaris.',
    'hero.slide2.title': 'Witness the Big Five',
    'hero.slide2.subtitle': 'Premium Wildlife Encounters',
    'hero.slide2.description': 'Get up close with majestic lions, elephants, and more in their natural habitat.',
    'hero.slide3.title': 'Paradise Awaits',
    'hero.slide3.subtitle': 'Coastal Beach Escapes',
    'hero.slide3.description': 'Relax on pristine Diani Beach shores after your thrilling safari adventure.',
    'hero.slide4.title': 'The Great Migration',
    'hero.slide4.subtitle': 'Once in a Lifetime Experience',
    'hero.slide4.description': 'Witness millions of wildebeest and zebras on their epic journey across the Serengeti.',
    'hero.exploreSafaris': 'Explore Safaris',
    'hero.planTrip': 'Plan Your Trip',
    
    // About Section
    'about.tagline': 'About Gokyle Tours & Safaris',
    'about.title': 'More Than a Dream',
    'about.content1': 'Based in the stunning coastal town of Diani Beach, Kenya, Gokyle Tours & Safaris is your gateway to authentic African adventures. Under the leadership of Lucky Katama Katoya, we\'ve been crafting extraordinary travel experiences that showcase the best of Kenya and Tanzania.',
    'about.content2': 'Whether you\'re seeking the thrill of a wildlife safari, the serenity of pristine beaches, or the richness of local culture, we curate journeys that transform travel into lifelong memories.',
    'about.learnMore': 'Learn More About Us',
    
    // About Features
    'about.feature.guides': 'Expert Local Guides',
    'about.feature.guidesDesc': 'Our experienced guides know every trail, watering hole, and hidden gem across East Africa.',
    'about.feature.personalized': 'Personalized Service',
    'about.feature.personalizedDesc': 'Every safari is tailored to your preferences, ensuring a unique and memorable experience.',
    'about.feature.safety': 'Safety First',
    'about.feature.safetyDesc': 'Your safety is our priority. We maintain the highest standards in all our operations.',
    'about.feature.support': '24/7 Support',
    'about.feature.supportDesc': 'From booking to departure, our team is always available to assist you.',
    
    // Services Section
    'services.tagline': 'Our Services',
    'services.title': 'Complete Travel Solutions',
    'services.subtitle': 'From the moment you start planning to your safe return home, we handle every detail of your African adventure.',
    'services.wildlife': 'Wildlife Safaris',
    'services.wildlifeDesc': 'Experience thrilling game drives in world-renowned national parks and reserves.',
    'services.flights': 'Flight Bookings',
    'services.flightsDesc': 'Seamless domestic and international flight arrangements for your journey.',
    'services.transfers': 'Private Transfers',
    'services.transfersDesc': 'Comfortable airport pickups and transfers in modern vehicles.',
    'services.hotels': 'Hotel Reservations',
    'services.hotelsDesc': 'Hand-picked accommodations from luxury lodges to boutique hotels.',
    'services.packages': 'Holiday Packages',
    'services.packagesDesc': 'All-inclusive vacation packages tailored to your preferences.',
    'services.corporate': 'Group & Corporate',
    'services.corporateDesc': 'Specialized travel solutions for groups and corporate clients.',
    
    // Destinations Section
    'destinations.tagline': 'Our Destinations',
    'destinations.title': 'Explore East Africa',
    'destinations.subtitle': 'From the vast savannas of the Masai Mara to the pristine beaches of the Kenyan coast, discover the best destinations Africa has to offer.',
    'destinations.viewAll': 'View All Destinations',
    'destinations.masaiMara': 'Masai Mara',
    'destinations.masaiMaraDesc': 'Home to the Great Migration and abundant wildlife year-round.',
    'destinations.serengeti': 'Serengeti',
    'destinations.serengetiDesc': 'Endless plains hosting millions of wildebeest and zebras.',
    'destinations.amboseli': 'Amboseli',
    'destinations.amboseliDesc': 'Iconic views of Mount Kilimanjaro with elephant herds.',
    'destinations.dianiBeach': 'Diani Beach',
    'destinations.dianiBeachDesc': 'Pristine white sand beaches and crystal-clear waters.',
    'destinations.ngorongoro': 'Ngorongoro Crater',
    'destinations.ngorongoroDesc': 'A UNESCO World Heritage Site with unique ecosystems.',
    'destinations.lakeNakuru': 'Lake Nakuru',
    'destinations.lakeNakuruDesc': 'Famous for flamingos and rhino conservation.',
    
    // Testimonials Section
    'testimonials.tagline': 'Testimonials',
    'testimonials.title': 'What Our Guests Say',
    'testimonials.subtitle': 'Don\'t just take our word for it. Here\'s what travelers from around the world have to say about their adventures with us.',
    
    // CTA Section
    'cta.tagline': 'Ready for Adventure?',
    'cta.title': 'Start Planning Your Dream Safari Today',
    'cta.subtitle': 'Let our experts craft a personalized itinerary that brings your African adventure to life. Contact us for a free consultation.',
    'cta.quote': 'Get a Free Quote',
    'cta.whatsapp': 'WhatsApp Us',
    
    // Footer
    'footer.description': 'Your trusted partner for unforgettable African safari adventures. Experience Kenya and Tanzania like never before.',
    'footer.quickLinks': 'Quick Links',
    'footer.popularDestinations': 'Popular Destinations',
    'footer.contactUs': 'Contact Us',
    'footer.aboutUs': 'About Us',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    
    // Safaris Page
    'safaris.heroTagline': 'Unforgettable Adventures',
    'safaris.heroTitle': 'Safari Packages',
    'safaris.heroSubtitle': 'Handcrafted safari experiences in Kenya and Tanzania',
    'safaris.planSafari': 'Plan Your Safari',
    'safaris.featuredTagline': 'Most Popular',
    'safaris.featuredTitle': 'Featured Safaris',
    'safaris.featuredSubtitle': 'Our most sought-after safari experiences, crafted for unforgettable memories',
    'safaris.featured': 'Featured',
    'safaris.bookNow': 'Book Now',
    'safaris.styleTagline': 'Choose Your Style',
    'safaris.styleTitle': 'Safari Experiences',
    'safaris.allTagline': 'All Packages',
    'safaris.allTitle': 'Browse All Safaris',
    'safaris.allPackages': 'All Packages',
    'safaris.dayExcursions': 'Day Excursions',
    'safaris.jeepSafaris': 'Jeep Safaris',
    'safaris.flyInSafaris': 'Fly-in Safaris',
    'safaris.importantInfo': 'Important Information',
    'safaris.bookingPricing': 'Booking & Pricing',
    'safaris.bookingInfo1': 'Other lodges and tented camps available on request',
    'safaris.bookingInfo2': 'Minimum number of participants may apply',
    'safaris.bookingInfo3': 'Single room supplement applicable',
    'safaris.bookingInfo4': 'Children (2-11 years): 50% discount on excursions/bus safaris, 25% on flight safaris',
    'safaris.paymentCancellation': 'Payment & Cancellation',
    'safaris.paymentInfo1': 'Payment: USD / Euro / Traveller\'s Cheques / MasterCard / Visa',
    'safaris.paymentInfo2': '48–24 hrs before safari: 50% cancellation fee',
    'safaris.paymentInfo3': '0–24 hrs before safari: 100% cancellation fee',
    'safaris.paymentInfo4': 'Fully insured according to IATA International Standards',
    'safaris.whyBook': 'Why Book With Gokyle',
    'safaris.whyBookSubtitle': 'We\'re not just tour operators – we\'re passionate about sharing the magic of East Africa',
    'safaris.expertGuides': 'Expert Guides',
    'safaris.expertGuidesDesc': 'Knowledgeable local guides with years of experience',
    'safaris.bestPrices': 'Best Prices',
    'safaris.bestPricesDesc': 'Competitive rates with no hidden fees',
    'safaris.flexibleBooking': 'Flexible Booking',
    'safaris.flexibleBookingDesc': 'Easy modifications and cancellation policies',
    'safaris.support': '24/7 Support',
    'safaris.supportDesc': 'Always here to assist during your trip',
    'safaris.customTagline': 'Custom Safari',
    'safaris.customTitle': 'Can\'t Find What You\'re Looking For?',
    'safaris.customSubtitle': 'Let us create a bespoke safari experience tailored to your dreams',
    'safaris.requestCustom': 'Request Custom Safari',
    
    // Category Labels
    'category.excursion': 'Day Excursion',
    'category.jeepSafari': 'Jeep Safari',
    'category.flyInSafari': 'Fly-in Safari',
    
    // Booking Modal
    'booking.title': 'Book Your Safari',
    'booking.selectPackage': 'Select a package below',
    'booking.selectSafariPackage': 'Select Safari Package',
    'booking.chooseSafari': 'Choose a safari package',
    'booking.packageDetails': 'Package Details',
    'booking.duration': 'Duration',
    'booking.location': 'Location',
    'booking.price': 'Price',
    'booking.highlights': 'Highlights',
    'booking.yourDetails': 'Your Details',
    'booking.fullName': 'Full Name',
    'booking.emailAddress': 'Email Address',
    'booking.phoneNumber': 'Phone Number',
    'booking.countryOfOrigin': 'Country of Origin',
    'booking.numberOfTravelers': 'Number of Travelers',
    'booking.preferredDate': 'Preferred Travel Date',
    'booking.specialRequests': 'Any special requests or questions?',
    'booking.submitMethod': 'Choose how you\'d like to submit your booking request:',
    'booking.submitBooking': 'Submit Booking',
    'booking.bookOnWhatsApp': 'Book on WhatsApp',
    'booking.emailOpened': 'Email client opened',
    'booking.emailOpenedDesc': 'Please send the email to complete your booking request.',
    'booking.whatsappOpened': 'WhatsApp opened',
    'booking.whatsappOpenedDesc': 'Complete your booking request on WhatsApp.',
    'booking.nameRequired': 'Name is required',
    'booking.emailRequired': 'Valid email is required',
    'booking.phoneRequired': 'Phone number is required',
    'booking.countryRequired': 'Please select your country of origin',
    'booking.packageRequired': 'Please select a safari package',
    'booking.bookingRequest': 'SAFARI BOOKING REQUEST',
    'booking.customerDetails': 'CUSTOMER DETAILS',
    'booking.notSpecified': 'Not specified',
    'booking.flexible': 'Flexible',
    'booking.noMessage': 'No additional message',
    'booking.additionalMessage': 'Additional Message',
    
    // Common
    'common.kenya': 'Kenya',
    'common.tanzania': 'Tanzania',
    
    // About Page
    'about.heroTagline': 'Our Story',
    'about.heroTitle': 'About Us',
    'about.heroSubtitle': 'Crafting unforgettable African adventures since our founding in Diani Beach, Kenya.',
    'about.mainTitle': 'More Than a Dream',
    'about.mainP1': 'GoKYLE Tours and Safaris is an adventurous Kenya-based tour company operating from the stunning coastal paradise of Diani Beach. We are more than just a travel company—we are your gateway to experiencing the raw beauty, rich culture, and incredible wildlife that make East Africa one of the world\'s most captivating destinations.',
    'about.mainP2': 'We offer both luxury and budget safaris, creating unforgettable journeys across Kenya\'s iconic wildlife destinations and pristine coastal escapes. From the thundering herds of the Great Migration in the Masai Mara to the snow-capped peaks of Mount Kilimanjaro, from ancient Swahili trading towns to the turquoise waters of the Indian Ocean—we unlock the wonders of East Africa for travelers from around the world.',
    'about.mainP3': 'With experienced local guides who share an intimate knowledge of the land and its stories, flexible itineraries tailored to your dreams, and an unwavering commitment to authentic experiences, we deliver safari adventures filled with discovery, comfort, and joy.',
    'about.yearsExcellence': 'Years of Excellence',
    'about.valuesTagline': 'What Drives Us',
    'about.valuesTitle': 'Our Values',
    'about.value.passion': 'Passion for Africa',
    'about.value.passionDesc': 'Our love for this land drives everything we do.',
    'about.value.safety': 'Safety & Trust',
    'about.value.safetyDesc': 'Your wellbeing is our top priority on every journey.',
    'about.value.personal': 'Personal Touch',
    'about.value.personalDesc': 'Every guest is family, every trip is unique.',
    'about.value.excellence': 'Excellence',
    'about.value.excellenceDesc': 'We never compromise on quality and service.',
    'about.value.sustainability': 'Sustainability',
    'about.value.sustainabilityDesc': 'Protecting wildlife and supporting local communities.',
    'about.value.adventure': 'Adventure',
    'about.value.adventureDesc': 'Creating extraordinary experiences that last forever.',
    'about.directorTagline': 'Leadership',
    'about.directorTitle': 'Meet Our Director',
    'about.founderDirector': 'Founder & Director',
    'about.directorBio1': 'With a lifelong passion for wildlife conservation and hospitality, Lucky founded Gokyle Tours & Safaris to share the magic of East Africa with travelers from around the globe.',
    'about.directorBio2': 'Born and raised on the beautiful Kenyan coast, Lucky brings an intimate knowledge of the land, its wildlife, and its people to every safari experience. His commitment to exceptional service, authentic experiences, and sustainable tourism has made Gokyle a trusted name in African travel.',
    'about.directorBio3': 'Lucky personally oversees every aspect of the business, ensuring that each guest receives the attention, care, and unforgettable memories that have become the hallmark of Gokyle Tours & Safaris.',
    
    // Destinations Page
    'dest.heroTagline': 'Explore East Africa',
    'dest.heroTitleAll': 'Our Destinations',
    'dest.heroSubtitleAll': 'From vast savannas to pristine beaches, discover the best of Kenya and Tanzania',
    'dest.heroSubtitleKenya': 'Discover the magic of Kenya\'s wildlife and beaches',
    'dest.heroSubtitleTanzania': 'Explore Tanzania\'s endless plains and majestic mountains',
    'dest.destinations': 'Destinations',
    'dest.incredibleDestinations': 'incredible destinations',
    'dest.viewAllKenya': 'View All Kenya Destinations',
    'dest.viewAllTanzania': 'View All Tanzania Destinations',
    'dest.planJourney': 'Plan Your Journey',
    'dest.exploreRegion': 'Explore the Region',
    'dest.exploreRegionDesc': 'East Africa offers incredible diversity, from snow-capped mountains to tropical beaches, and everything in between.',
    'dest.destinationsInKenya': 'Destinations in Kenya & Tanzania',
    'dest.nationalParks': 'National Parks & Reserves',
    'dest.curatedExperiences': 'Curated Experiences',
    
    // Blog Page
    'blog.heroTagline': 'Stories & Insights',
    'blog.heroTitle': 'Our Blog',
    'blog.heroSubtitle': 'Travel tips, destination guides, and safari stories',
    'blog.featuredArticles': 'Featured Articles',
    'blog.readMore': 'Read More',
    'blog.allCategory': 'All',
    'blog.stayUpdated': 'Stay Updated',
    'blog.newsletterDesc': 'Subscribe to our newsletter for travel tips, exclusive offers, and safari inspiration.',
    'blog.enterEmail': 'Enter your email',
    'blog.subscribe': 'Subscribe',
    'blog.backToBlog': 'Back to Blog',
    'blog.backToAllArticles': 'Back to All Articles',
    'blog.bookExperience': 'Book This Experience',
    
    // FAQ Page
    'faq.heroTagline': 'Questions & Answers',
    'faq.heroTitle': 'FAQ',
    'faq.heroSubtitle': 'Find answers to commonly asked questions about our safaris and services.',
    'faq.category.booking': 'Booking & Payments',
    'faq.category.safari': 'Safari Experience',
    'faq.category.accommodation': 'Accommodation & Transport',
    'faq.category.health': 'Health & Requirements',
    'faq.q1': 'How do I book a safari with Gokyle Tours?',
    'faq.a1': 'You can book through our website contact form, email us at gokyletours@gmail.com, or reach us via WhatsApp at +254 742 196 613. We\'ll discuss your preferences and create a personalized itinerary.',
    'faq.q2': 'What payment methods do you accept?',
    'faq.a2': 'We accept bank transfers, credit cards, and mobile payments (M-Pesa). A deposit of 30% is required to confirm your booking, with the balance due 30 days before your safari.',
    'faq.q3': 'What is your cancellation policy?',
    'faq.a3': 'Cancellations made 60+ days before departure receive a full refund minus a small admin fee. 30-60 days: 50% refund. Less than 30 days: No refund. We recommend travel insurance.',
    'faq.q4': 'Are your prices inclusive?',
    'faq.a4': 'Our packages typically include accommodation, meals as specified, park fees, game drives, and transfers. International flights, visas, travel insurance, and personal expenses are usually excluded.',
    'faq.q5': 'What is the best time to visit Kenya and Tanzania?',
    'faq.a5': 'The dry seasons (June-October and January-February) are ideal for wildlife viewing. The Great Migration in Masai Mara peaks from July to October. Green season (November-May) offers beautiful landscapes and fewer tourists.',
    'faq.q6': 'What should I pack for a safari?',
    'faq.a6': 'Neutral-colored, lightweight clothing, comfortable walking shoes, sun hat, sunscreen, insect repellent, binoculars, camera with zoom lens, and any personal medications. Evenings can be cool, so bring layers.',
    'faq.q7': 'Is it safe to go on safari?',
    'faq.a7': 'Yes! Our experienced guides prioritize your safety at all times. We follow strict protocols, maintain our vehicles regularly, and have extensive knowledge of wildlife behavior.',
    'faq.q8': 'Can I see the Big Five on your safaris?',
    'faq.a8': 'Absolutely! The Masai Mara, Serengeti, and other parks we visit are home to all Big Five animals (lion, leopard, elephant, buffalo, and rhino). Sightings are common but never guaranteed in the wild.',
    'faq.q9': 'What types of accommodation do you offer?',
    'faq.a9': 'We offer a range from luxury lodges and tented camps to mid-range hotels and eco-friendly camps. All accommodations are carefully selected for comfort, location, and service quality.',
    'faq.q10': 'What vehicles do you use for safaris?',
    'faq.a10': 'We use 4x4 Land Cruisers and safari vans with pop-up roofs for optimal wildlife viewing. All vehicles are well-maintained, equipped with charging ports, and have experienced driver-guides.',
    'faq.q11': 'Do you offer airport transfers?',
    'faq.a11': 'Yes! We provide comfortable private transfers from Nairobi\'s JKIA, Mombasa\'s Moi International Airport, and other regional airports to your accommodation or safari starting point.',
    'faq.q12': 'Do I need vaccinations for Kenya/Tanzania?',
    'faq.a12': 'Yellow fever vaccination is required if arriving from an endemic country. We recommend consulting your doctor about malaria prophylaxis, hepatitis, and typhoid vaccinations before travel.',
    'faq.q13': 'What visa do I need?',
    'faq.a13': 'Most nationalities can obtain an e-visa or visa on arrival for Kenya and Tanzania. Check your country\'s requirements and ensure your passport is valid for at least 6 months.',
    'faq.q14': 'Is travel insurance required?',
    'faq.a14': 'Yes, we strongly recommend comprehensive travel insurance covering medical emergencies, evacuation, trip cancellation, and baggage loss. This is mandatory for most of our tours.',
    'faq.stillQuestions': 'Still have questions?',
    'faq.stillQuestionsDesc': 'Our team is ready to help you plan your perfect safari adventure.',
    'faq.contactUs': 'Contact Us',
    
    // Contact Page
    'contact.heroTagline': 'Get In Touch',
    'contact.heroTitle': 'Contact Us',
    'contact.heroSubtitle': 'Ready to start your African adventure? We\'d love to hear from you.',
    'contact.planSafari': 'Let\'s Plan Your Dream Safari',
    'contact.planSafariDesc': 'Whether you\'re planning a romantic getaway, family adventure, or group expedition, our team is here to help create your perfect African experience.',
    'contact.phoneWhatsApp': 'Phone / WhatsApp',
    'contact.email': 'Email',
    'contact.location': 'Location',
    'contact.businessHours': 'Business Hours',
    'contact.mondaySaturday': 'Monday - Saturday: 8:00 AM - 6:00 PM',
    'contact.sunday': 'Sunday: 9:00 AM - 4:00 PM',
    'contact.followUs': 'Follow Us',
    'contact.chatWhatsApp': 'Chat on WhatsApp',
    'contact.sendMessage': 'Send Us a Message',
    'contact.fullName': 'Full Name',
    'contact.yourName': 'Your name',
    'contact.emailAddress': 'Email Address',
    'contact.phoneNumber': 'Phone Number',
    'contact.subject': 'Subject',
    'contact.safariInquiry': 'Safari Inquiry',
    'contact.yourMessage': 'Your Message',
    'contact.dreamSafari': 'Tell us about your dream safari...',
    'contact.send': 'Send Message',
    'contact.emailOpening': 'Opening email client...',
    'contact.emailOpeningDesc': 'Your message will be sent via your email application.',
    'contact.findUs': 'Find Us',
    'contact.ourLocation': 'Our Location',
    'contact.locationDesc': 'Visit us at our office in the beautiful coastal town of Diani Beach, Kenya.',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.destinations': 'Reiseziele',
    'nav.safaris': 'Safaris',
    'nav.services': 'Leistungen',
    'nav.gallery': 'Galerie',
    'nav.blog': 'Blog',
    'nav.qa': 'FAQ',
    'nav.contact': 'Kontakt',
    'nav.bookNow': 'Jetzt Buchen',
    'nav.kenya': 'Kenia',
    'nav.tanzania': 'Tansania',
    
    // Hero Slider
    'hero.slide1.title': 'Entdecken Sie die Magie Afrikas',
    'hero.slide1.subtitle': 'Unvergessliche Safari-Abenteuer',
    'hero.slide1.description': 'Erleben Sie die unberührte Schönheit Kenias und Tansanias mit unseren fachmännisch zusammengestellten Wildtier-Safaris.',
    'hero.slide2.title': 'Erleben Sie die Big Five',
    'hero.slide2.subtitle': 'Premium Wildtier-Begegnungen',
    'hero.slide2.description': 'Kommen Sie majestätischen Löwen, Elefanten und mehr in ihrem natürlichen Lebensraum ganz nah.',
    'hero.slide3.title': 'Das Paradies wartet',
    'hero.slide3.subtitle': 'Küsten-Strand-Ausflüge',
    'hero.slide3.description': 'Entspannen Sie an den unberührten Stränden von Diani Beach nach Ihrem aufregenden Safari-Abenteuer.',
    'hero.slide4.title': 'Die Große Migration',
    'hero.slide4.subtitle': 'Ein Erlebnis fürs Leben',
    'hero.slide4.description': 'Erleben Sie Millionen von Gnus und Zebras auf ihrer epischen Reise durch die Serengeti.',
    'hero.exploreSafaris': 'Safaris Erkunden',
    'hero.planTrip': 'Reise Planen',
    
    // About Section
    'about.tagline': 'Über Gokyle Tours & Safaris',
    'about.title': 'Mehr als ein Traum',
    'about.content1': 'Mit Sitz in der atemberaubenden Küstenstadt Diani Beach, Kenia, ist Gokyle Tours & Safaris Ihr Tor zu authentischen afrikanischen Abenteuern. Unter der Leitung von Lucky Katama Katoya gestalten wir außergewöhnliche Reiseerlebnisse, die das Beste von Kenia und Tansania präsentieren.',
    'about.content2': 'Ob Sie den Nervenkitzel einer Wildtier-Safari, die Ruhe unberührter Strände oder den Reichtum der lokalen Kultur suchen, wir kuratieren Reisen, die Urlaub in lebenslange Erinnerungen verwandeln.',
    'about.learnMore': 'Mehr über uns erfahren',
    
    // About Features
    'about.feature.guides': 'Erfahrene lokale Guides',
    'about.feature.guidesDesc': 'Unsere erfahrenen Guides kennen jeden Pfad, jede Wasserstelle und jeden verborgenen Schatz in Ostafrika.',
    'about.feature.personalized': 'Persönlicher Service',
    'about.feature.personalizedDesc': 'Jede Safari wird nach Ihren Wünschen gestaltet, um ein einzigartiges und unvergessliches Erlebnis zu gewährleisten.',
    'about.feature.safety': 'Sicherheit zuerst',
    'about.feature.safetyDesc': 'Ihre Sicherheit hat Priorität. Wir halten bei allen unseren Abläufen die höchsten Standards ein.',
    'about.feature.support': '24/7 Unterstützung',
    'about.feature.supportDesc': 'Von der Buchung bis zur Abreise ist unser Team immer für Sie da.',
    
    // Services Section
    'services.tagline': 'Unsere Leistungen',
    'services.title': 'Komplette Reiselösungen',
    'services.subtitle': 'Vom Beginn Ihrer Planung bis zur sicheren Heimkehr kümmern wir uns um jedes Detail Ihres afrikanischen Abenteuers.',
    'services.wildlife': 'Wildtier-Safaris',
    'services.wildlifeDesc': 'Erleben Sie aufregende Pirschfahrten in weltbekannten Nationalparks und Reservaten.',
    'services.flights': 'Flugbuchungen',
    'services.flightsDesc': 'Nahtlose Inlands- und internationale Flugarrangements für Ihre Reise.',
    'services.transfers': 'Private Transfers',
    'services.transfersDesc': 'Komfortable Flughafen-Abholungen und Transfers in modernen Fahrzeugen.',
    'services.hotels': 'Hotelreservierungen',
    'services.hotelsDesc': 'Handverlesene Unterkünfte von Luxuslodges bis zu Boutique-Hotels.',
    'services.packages': 'Urlaubspakete',
    'services.packagesDesc': 'All-inclusive Urlaubspakete nach Ihren Wünschen.',
    'services.corporate': 'Gruppen & Firmen',
    'services.corporateDesc': 'Spezialisierte Reiselösungen für Gruppen und Firmenkunden.',
    
    // Destinations Section
    'destinations.tagline': 'Unsere Reiseziele',
    'destinations.title': 'Ostafrika Erkunden',
    'destinations.subtitle': 'Von den weiten Savannen der Masai Mara bis zu den unberührten Stränden der kenianischen Küste – entdecken Sie die besten Reiseziele, die Afrika zu bieten hat.',
    'destinations.viewAll': 'Alle Reiseziele ansehen',
    'destinations.masaiMara': 'Masai Mara',
    'destinations.masaiMaraDesc': 'Heimat der Großen Migration und ganzjährig reichhaltiger Tierwelt.',
    'destinations.serengeti': 'Serengeti',
    'destinations.serengetiDesc': 'Endlose Ebenen mit Millionen von Gnus und Zebras.',
    'destinations.amboseli': 'Amboseli',
    'destinations.amboseliDesc': 'Ikonische Aussicht auf den Kilimandscharo mit Elefantenherden.',
    'destinations.dianiBeach': 'Diani Beach',
    'destinations.dianiBeachDesc': 'Unberührte weiße Sandstrände und kristallklares Wasser.',
    'destinations.ngorongoro': 'Ngorongoro-Krater',
    'destinations.ngorongoroDesc': 'UNESCO-Weltkulturerbe mit einzigartigen Ökosystemen.',
    'destinations.lakeNakuru': 'Nakurusee',
    'destinations.lakeNakuruDesc': 'Berühmt für Flamingos und Nashornschutz.',
    
    // Testimonials Section
    'testimonials.tagline': 'Bewertungen',
    'testimonials.title': 'Was unsere Gäste sagen',
    'testimonials.subtitle': 'Verlassen Sie sich nicht nur auf unser Wort. Hier ist, was Reisende aus aller Welt über ihre Abenteuer mit uns sagen.',
    
    // CTA Section
    'cta.tagline': 'Bereit für das Abenteuer?',
    'cta.title': 'Beginnen Sie noch heute mit der Planung Ihrer Traumsafari',
    'cta.subtitle': 'Lassen Sie unsere Experten eine personalisierte Reiseroute erstellen, die Ihr afrikanisches Abenteuer zum Leben erweckt. Kontaktieren Sie uns für eine kostenlose Beratung.',
    'cta.quote': 'Kostenloses Angebot anfordern',
    'cta.whatsapp': 'WhatsApp',
    
    // Footer
    'footer.description': 'Ihr vertrauenswürdiger Partner für unvergessliche afrikanische Safari-Abenteuer. Erleben Sie Kenia und Tansania wie nie zuvor.',
    'footer.quickLinks': 'Schnelllinks',
    'footer.popularDestinations': 'Beliebte Reiseziele',
    'footer.contactUs': 'Kontakt',
    'footer.aboutUs': 'Über Uns',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'Nutzungsbedingungen',
    
    // Safaris Page
    'safaris.heroTagline': 'Unvergessliche Abenteuer',
    'safaris.heroTitle': 'Safari-Pakete',
    'safaris.heroSubtitle': 'Handgefertigte Safari-Erlebnisse in Kenia und Tansania',
    'safaris.planSafari': 'Safari planen',
    'safaris.featuredTagline': 'Beliebteste',
    'safaris.featuredTitle': 'Empfohlene Safaris',
    'safaris.featuredSubtitle': 'Unsere beliebtesten Safari-Erlebnisse, gestaltet für unvergessliche Erinnerungen',
    'safaris.featured': 'Empfohlen',
    'safaris.bookNow': 'Jetzt Buchen',
    'safaris.styleTagline': 'Wählen Sie Ihren Stil',
    'safaris.styleTitle': 'Safari-Erlebnisse',
    'safaris.allTagline': 'Alle Pakete',
    'safaris.allTitle': 'Alle Safaris durchsuchen',
    'safaris.allPackages': 'Alle Pakete',
    'safaris.dayExcursions': 'Tagesausflüge',
    'safaris.jeepSafaris': 'Jeep-Safaris',
    'safaris.flyInSafaris': 'Flugsafaris',
    'safaris.importantInfo': 'Wichtige Informationen',
    'safaris.bookingPricing': 'Buchung & Preise',
    'safaris.bookingInfo1': 'Andere Lodges und Zeltcamps auf Anfrage verfügbar',
    'safaris.bookingInfo2': 'Mindestteilnehmerzahl kann gelten',
    'safaris.bookingInfo3': 'Einzelzimmerzuschlag anwendbar',
    'safaris.bookingInfo4': 'Kinder (2-11 Jahre): 50% Rabatt bei Ausflügen/Bus-Safaris, 25% bei Flugsafaris',
    'safaris.paymentCancellation': 'Zahlung & Stornierung',
    'safaris.paymentInfo1': 'Zahlung: USD / Euro / Reiseschecks / MasterCard / Visa',
    'safaris.paymentInfo2': '48–24 Std. vor Safari: 50% Stornogebühr',
    'safaris.paymentInfo3': '0–24 Std. vor Safari: 100% Stornogebühr',
    'safaris.paymentInfo4': 'Vollversichert nach IATA International Standards',
    'safaris.whyBook': 'Warum bei Gokyle buchen',
    'safaris.whyBookSubtitle': 'Wir sind nicht nur Reiseveranstalter – wir teilen mit Leidenschaft die Magie Ostafrikas',
    'safaris.expertGuides': 'Erfahrene Guides',
    'safaris.expertGuidesDesc': 'Sachkundige lokale Guides mit jahrelanger Erfahrung',
    'safaris.bestPrices': 'Beste Preise',
    'safaris.bestPricesDesc': 'Wettbewerbsfähige Preise ohne versteckte Gebühren',
    'safaris.flexibleBooking': 'Flexible Buchung',
    'safaris.flexibleBookingDesc': 'Einfache Änderungen und Stornierungsrichtlinien',
    'safaris.support': '24/7 Unterstützung',
    'safaris.supportDesc': 'Immer für Sie da während Ihrer Reise',
    'safaris.customTagline': 'Individuelle Safari',
    'safaris.customTitle': 'Nicht das Richtige gefunden?',
    'safaris.customSubtitle': 'Lassen Sie uns ein maßgeschneidertes Safari-Erlebnis nach Ihren Träumen gestalten',
    'safaris.requestCustom': 'Individuelle Safari anfragen',
    
    // Category Labels
    'category.excursion': 'Tagesausflug',
    'category.jeepSafari': 'Jeep-Safari',
    'category.flyInSafari': 'Flugsafari',
    
    // Booking Modal
    'booking.title': 'Safari buchen',
    'booking.selectPackage': 'Wählen Sie unten ein Paket',
    'booking.selectSafariPackage': 'Safari-Paket auswählen',
    'booking.chooseSafari': 'Wählen Sie ein Safari-Paket',
    'booking.packageDetails': 'Paketdetails',
    'booking.duration': 'Dauer',
    'booking.location': 'Ort',
    'booking.price': 'Preis',
    'booking.highlights': 'Highlights',
    'booking.yourDetails': 'Ihre Daten',
    'booking.fullName': 'Vollständiger Name',
    'booking.emailAddress': 'E-Mail-Adresse',
    'booking.phoneNumber': 'Telefonnummer',
    'booking.countryOfOrigin': 'Herkunftsland',
    'booking.numberOfTravelers': 'Anzahl der Reisenden',
    'booking.preferredDate': 'Gewünschtes Reisedatum',
    'booking.specialRequests': 'Besondere Wünsche oder Fragen?',
    'booking.submitMethod': 'Wählen Sie, wie Sie Ihre Buchungsanfrage senden möchten:',
    'booking.submitBooking': 'Buchung absenden',
    'booking.bookOnWhatsApp': 'Über WhatsApp buchen',
    'booking.emailOpened': 'E-Mail-Programm geöffnet',
    'booking.emailOpenedDesc': 'Bitte senden Sie die E-Mail, um Ihre Buchungsanfrage abzuschließen.',
    'booking.whatsappOpened': 'WhatsApp geöffnet',
    'booking.whatsappOpenedDesc': 'Vervollständigen Sie Ihre Buchungsanfrage auf WhatsApp.',
    'booking.nameRequired': 'Name ist erforderlich',
    'booking.emailRequired': 'Gültige E-Mail ist erforderlich',
    'booking.phoneRequired': 'Telefonnummer ist erforderlich',
    'booking.countryRequired': 'Bitte wählen Sie Ihr Herkunftsland',
    'booking.packageRequired': 'Bitte wählen Sie ein Safari-Paket',
    'booking.bookingRequest': 'SAFARI-BUCHUNGSANFRAGE',
    'booking.customerDetails': 'KUNDENDATEN',
    'booking.notSpecified': 'Nicht angegeben',
    'booking.flexible': 'Flexibel',
    'booking.noMessage': 'Keine zusätzliche Nachricht',
    'booking.additionalMessage': 'Zusätzliche Nachricht',
    
    // Common
    'common.kenya': 'Kenia',
    'common.tanzania': 'Tansania',
    
    // About Page
    'about.heroTagline': 'Unsere Geschichte',
    'about.heroTitle': 'Über uns',
    'about.heroSubtitle': 'Wir gestalten unvergessliche afrikanische Abenteuer seit unserer Gründung in Diani Beach, Kenia.',
    'about.mainTitle': 'Mehr als ein Traum',
    'about.mainP1': 'GoKYLE Tours and Safaris ist ein abenteuerliches, in Kenia ansässiges Reiseunternehmen mit Sitz im atemberaubenden Küstenparadies Diani Beach. Wir sind mehr als nur ein Reiseunternehmen – wir sind Ihr Tor zur rohen Schönheit, reichen Kultur und unglaublichen Tierwelt, die Ostafrika zu einem der faszinierendsten Reiseziele der Welt machen.',
    'about.mainP2': 'Wir bieten sowohl Luxus- als auch Budget-Safaris an und gestalten unvergessliche Reisen zu Kenias berühmten Wildtierzielen und unberührten Küstenfluchten. Von den donnernden Herden der Großen Migration in der Masai Mara bis zu den schneebedeckten Gipfeln des Kilimandscharo, von alten Swahili-Handelsstädten bis zum türkisfarbenen Wasser des Indischen Ozeans – wir erschließen die Wunder Ostafrikas für Reisende aus aller Welt.',
    'about.mainP3': 'Mit erfahrenen lokalen Guides, die ein tiefes Wissen über das Land und seine Geschichten teilen, flexiblen Reiserouten nach Ihren Träumen und einem unerschütterlichen Engagement für authentische Erlebnisse liefern wir Safari-Abenteuer voller Entdeckung, Komfort und Freude.',
    'about.yearsExcellence': 'Jahre Exzellenz',
    'about.valuesTagline': 'Was uns antreibt',
    'about.valuesTitle': 'Unsere Werte',
    'about.value.passion': 'Leidenschaft für Afrika',
    'about.value.passionDesc': 'Unsere Liebe zu diesem Land treibt alles an, was wir tun.',
    'about.value.safety': 'Sicherheit & Vertrauen',
    'about.value.safetyDesc': 'Ihr Wohlbefinden hat bei jeder Reise oberste Priorität.',
    'about.value.personal': 'Persönliche Note',
    'about.value.personalDesc': 'Jeder Gast ist Familie, jede Reise ist einzigartig.',
    'about.value.excellence': 'Exzellenz',
    'about.value.excellenceDesc': 'Wir machen bei Qualität und Service keine Kompromisse.',
    'about.value.sustainability': 'Nachhaltigkeit',
    'about.value.sustainabilityDesc': 'Schutz der Tierwelt und Unterstützung lokaler Gemeinschaften.',
    'about.value.adventure': 'Abenteuer',
    'about.value.adventureDesc': 'Wir schaffen außergewöhnliche Erlebnisse, die ewig in Erinnerung bleiben.',
    'about.directorTagline': 'Führung',
    'about.directorTitle': 'Lernen Sie unseren Direktor kennen',
    'about.founderDirector': 'Gründer & Direktor',
    'about.directorBio1': 'Mit einer lebenslangen Leidenschaft für Wildtierschutz und Gastfreundschaft gründete Lucky Gokyle Tours & Safaris, um die Magie Ostafrikas mit Reisenden aus der ganzen Welt zu teilen.',
    'about.directorBio2': 'An der wunderschönen kenianischen Küste geboren und aufgewachsen, bringt Lucky ein intimes Wissen über das Land, seine Tierwelt und seine Menschen in jedes Safari-Erlebnis ein. Sein Engagement für außergewöhnlichen Service, authentische Erlebnisse und nachhaltigen Tourismus hat Gokyle zu einem vertrauenswürdigen Namen im afrikanischen Reisen gemacht.',
    'about.directorBio3': 'Lucky überwacht persönlich jeden Aspekt des Geschäfts und stellt sicher, dass jeder Gast die Aufmerksamkeit, Fürsorge und unvergesslichen Erinnerungen erhält, die zum Markenzeichen von Gokyle Tours & Safaris geworden sind.',
    
    // Destinations Page
    'dest.heroTagline': 'Ostafrika erkunden',
    'dest.heroTitleAll': 'Unsere Reiseziele',
    'dest.heroSubtitleAll': 'Von weiten Savannen bis zu unberührten Stränden – entdecken Sie das Beste von Kenia und Tansania',
    'dest.heroSubtitleKenya': 'Entdecken Sie die Magie von Kenias Tierwelt und Stränden',
    'dest.heroSubtitleTanzania': 'Erkunden Sie Tansanias endlose Ebenen und majestätische Berge',
    'dest.destinations': 'Reiseziele',
    'dest.incredibleDestinations': 'unglaubliche Reiseziele',
    'dest.viewAllKenya': 'Alle Reiseziele in Kenia ansehen',
    'dest.viewAllTanzania': 'Alle Reiseziele in Tansania ansehen',
    'dest.planJourney': 'Planen Sie Ihre Reise',
    'dest.exploreRegion': 'Erkunden Sie die Region',
    'dest.exploreRegionDesc': 'Ostafrika bietet unglaubliche Vielfalt, von schneebedeckten Bergen bis zu tropischen Stränden und allem dazwischen.',
    'dest.destinationsInKenya': 'Reiseziele in Kenia & Tansania',
    'dest.nationalParks': 'Nationalparks & Reservate',
    'dest.curatedExperiences': 'Kuratierte Erlebnisse',
    
    // Blog Page
    'blog.heroTagline': 'Geschichten & Einblicke',
    'blog.heroTitle': 'Unser Blog',
    'blog.heroSubtitle': 'Reisetipps, Reiseziel-Guides und Safari-Geschichten',
    'blog.featuredArticles': 'Empfohlene Artikel',
    'blog.readMore': 'Mehr lesen',
    'blog.allCategory': 'Alle',
    'blog.stayUpdated': 'Bleiben Sie informiert',
    'blog.newsletterDesc': 'Abonnieren Sie unseren Newsletter für Reisetipps, exklusive Angebote und Safari-Inspiration.',
    'blog.enterEmail': 'E-Mail eingeben',
    'blog.subscribe': 'Abonnieren',
    'blog.backToBlog': 'Zurück zum Blog',
    'blog.backToAllArticles': 'Zurück zu allen Artikeln',
    'blog.bookExperience': 'Dieses Erlebnis buchen',
    
    // FAQ Page
    'faq.heroTagline': 'Fragen & Antworten',
    'faq.heroTitle': 'FAQ',
    'faq.heroSubtitle': 'Finden Sie Antworten auf häufig gestellte Fragen zu unseren Safaris und Dienstleistungen.',
    'faq.category.booking': 'Buchung & Zahlung',
    'faq.category.safari': 'Safari-Erlebnis',
    'faq.category.accommodation': 'Unterkunft & Transport',
    'faq.category.health': 'Gesundheit & Anforderungen',
    'faq.q1': 'Wie buche ich eine Safari bei Gokyle Tours?',
    'faq.a1': 'Sie können über unser Kontaktformular auf der Website buchen, uns per E-Mail an gokyletours@gmail.com kontaktieren oder uns über WhatsApp unter +254 742 196 613 erreichen. Wir besprechen Ihre Wünsche und erstellen eine personalisierte Reiseroute.',
    'faq.q2': 'Welche Zahlungsmethoden akzeptieren Sie?',
    'faq.a2': 'Wir akzeptieren Banküberweisungen, Kreditkarten und mobile Zahlungen (M-Pesa). Eine Anzahlung von 30% ist erforderlich, um Ihre Buchung zu bestätigen, der Rest ist 30 Tage vor Ihrer Safari fällig.',
    'faq.q3': 'Was sind Ihre Stornierungsbedingungen?',
    'faq.a3': 'Stornierungen 60+ Tage vor Abreise erhalten eine volle Rückerstattung abzüglich einer kleinen Verwaltungsgebühr. 30-60 Tage: 50% Rückerstattung. Weniger als 30 Tage: Keine Rückerstattung. Wir empfehlen eine Reiseversicherung.',
    'faq.q4': 'Sind Ihre Preise inklusive?',
    'faq.a4': 'Unsere Pakete beinhalten in der Regel Unterkunft, Mahlzeiten wie angegeben, Parkgebühren, Pirschfahrten und Transfers. Internationale Flüge, Visa, Reiseversicherung und persönliche Ausgaben sind normalerweise nicht enthalten.',
    'faq.q5': 'Wann ist die beste Zeit, Kenia und Tansania zu besuchen?',
    'faq.a5': 'Die Trockenzeiten (Juni-Oktober und Januar-Februar) sind ideal für Wildtierbeobachtungen. Die Große Migration in der Masai Mara erreicht ihren Höhepunkt von Juli bis Oktober. Die Regenzeit (November-Mai) bietet wunderschöne Landschaften und weniger Touristen.',
    'faq.q6': 'Was sollte ich für eine Safari einpacken?',
    'faq.a6': 'Neutrale, leichte Kleidung, bequeme Wanderschuhe, Sonnenhut, Sonnencreme, Insektenschutz, Fernglas, Kamera mit Zoom-Objektiv und persönliche Medikamente. Abends kann es kühl werden, bringen Sie also Schichten mit.',
    'faq.q7': 'Ist es sicher, auf Safari zu gehen?',
    'faq.a7': 'Ja! Unsere erfahrenen Guides priorisieren Ihre Sicherheit zu jeder Zeit. Wir befolgen strenge Protokolle, warten unsere Fahrzeuge regelmäßig und haben umfassendes Wissen über Wildtierverhalten.',
    'faq.q8': 'Kann ich die Big Five auf Ihren Safaris sehen?',
    'faq.a8': 'Absolut! Die Masai Mara, Serengeti und andere Parks, die wir besuchen, beherbergen alle Big Five (Löwe, Leopard, Elefant, Büffel und Nashorn). Sichtungen sind häufig, aber in der Wildnis nie garantiert.',
    'faq.q9': 'Welche Unterkunftsarten bieten Sie an?',
    'faq.a9': 'Wir bieten eine Auswahl von Luxuslodges und Zeltcamps bis hin zu Mittelklasse-Hotels und umweltfreundlichen Camps. Alle Unterkünfte werden sorgfältig nach Komfort, Lage und Servicequalität ausgewählt.',
    'faq.q10': 'Welche Fahrzeuge nutzen Sie für Safaris?',
    'faq.a10': 'Wir verwenden 4x4 Land Cruiser und Safari-Vans mit Aufstelldächern für optimale Wildtierbeobachtung. Alle Fahrzeuge sind gut gewartet, mit Ladeanschlüssen ausgestattet und haben erfahrene Fahrer-Guides.',
    'faq.q11': 'Bieten Sie Flughafentransfers an?',
    'faq.a11': 'Ja! Wir bieten komfortable private Transfers vom JKIA in Nairobi, dem Moi International Airport in Mombasa und anderen regionalen Flughäfen zu Ihrer Unterkunft oder Ihrem Safari-Startpunkt.',
    'faq.q12': 'Brauche ich Impfungen für Kenia/Tansania?',
    'faq.a12': 'Eine Gelbfieberimpfung ist erforderlich, wenn Sie aus einem endemischen Land anreisen. Wir empfehlen, Ihren Arzt zu Malariaprophylaxe, Hepatitis- und Typhusimpfungen vor der Reise zu konsultieren.',
    'faq.q13': 'Welches Visum brauche ich?',
    'faq.a13': 'Die meisten Nationalitäten können ein E-Visum oder Visum bei Ankunft für Kenia und Tansania erhalten. Überprüfen Sie die Anforderungen Ihres Landes und stellen Sie sicher, dass Ihr Reisepass noch mindestens 6 Monate gültig ist.',
    'faq.q14': 'Ist eine Reiseversicherung erforderlich?',
    'faq.a14': 'Ja, wir empfehlen dringend eine umfassende Reiseversicherung, die medizinische Notfälle, Evakuierung, Reiserücktritt und Gepäckverlust abdeckt. Dies ist für die meisten unserer Touren obligatorisch.',
    'faq.stillQuestions': 'Noch Fragen?',
    'faq.stillQuestionsDesc': 'Unser Team ist bereit, Ihnen bei der Planung Ihres perfekten Safari-Abenteuers zu helfen.',
    'faq.contactUs': 'Kontaktieren Sie uns',
    
    // Contact Page
    'contact.heroTagline': 'Kontakt aufnehmen',
    'contact.heroTitle': 'Kontakt',
    'contact.heroSubtitle': 'Bereit, Ihr afrikanisches Abenteuer zu starten? Wir freuen uns, von Ihnen zu hören.',
    'contact.planSafari': 'Planen wir Ihre Traumsafari',
    'contact.planSafariDesc': 'Ob Sie einen romantischen Ausflug, ein Familienabenteuer oder eine Gruppenexpedition planen, unser Team ist hier, um Ihr perfektes afrikanisches Erlebnis zu gestalten.',
    'contact.phoneWhatsApp': 'Telefon / WhatsApp',
    'contact.email': 'E-Mail',
    'contact.location': 'Standort',
    'contact.businessHours': 'Geschäftszeiten',
    'contact.mondaySaturday': 'Montag - Samstag: 8:00 - 18:00',
    'contact.sunday': 'Sonntag: 9:00 - 16:00',
    'contact.followUs': 'Folgen Sie uns',
    'contact.chatWhatsApp': 'Auf WhatsApp chatten',
    'contact.sendMessage': 'Nachricht senden',
    'contact.fullName': 'Vollständiger Name',
    'contact.yourName': 'Ihr Name',
    'contact.emailAddress': 'E-Mail-Adresse',
    'contact.phoneNumber': 'Telefonnummer',
    'contact.subject': 'Betreff',
    'contact.safariInquiry': 'Safari-Anfrage',
    'contact.yourMessage': 'Ihre Nachricht',
    'contact.dreamSafari': 'Erzählen Sie uns von Ihrer Traumsafari...',
    'contact.send': 'Nachricht senden',
    'contact.emailOpening': 'E-Mail-Programm wird geöffnet...',
    'contact.emailOpeningDesc': 'Ihre Nachricht wird über Ihre E-Mail-Anwendung gesendet.',
    'contact.findUs': 'Finden Sie uns',
    'contact.ourLocation': 'Unser Standort',
    'contact.locationDesc': 'Besuchen Sie uns in unserem Büro in der wunderschönen Küstenstadt Diani Beach, Kenia.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
